- hosts: all
  become: yes
  tasks:
    - name: Install git
      yum:
       name: git
       state: present
       update_cache: yes
    - name: clone remote git repository
      git:
        repo: https://github.com/mohan0306/plyabooks.git
        dest: /var/www/html

