---
- hosts: all
  become: true

  tasks:
    - name: install httpd on servers
      yum: name=httpd update_cache=yes state=latest
      handlers:
        service:
        name=httpd
        state=restarted
        ---
   
